### PR TITLE
ADDED A CHECK BOX

### PR DESCRIPTION
**Pull request by NIKHIL2904**
i have added a checkbox to show bar chart.

### CODE REVIEW

**Review by uddeshyatyagi — COMMENTED** [review]
@NIKHIL2904 u need not add diabete.py in Heart-disease-prediction repository.U can remove that file(it need not be submitted/pushed)there.The changes u made in diabete.py of WebApp(Diabete Detection) are absolutely fine.Just remove the above file

**Comment by NIKHIL2904** [comment]
sir how to remove diabete.py in Heart-disease-prediction.

**Comment by uddeshyatyagi** [comment]
By git init command initiate your repo
Then in heart-disease prediction repository delete the file diabete.py.
Then then commit these changes and push them to your github repo

**Comment by uddeshyatyagi** [comment]
Excellent work,keep it up !

**Comment by NIKHIL2904** [comment]
Thank you sir.

**Pull request merged**
